# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: fastapi_app
#     ports:
#       - "8000:8000"
    

#   nginx:
#     build:
#       context: .
#       dockerfile: Dockerfile.nginx
#     container_name: nginx_proxy
#     ports:
#       - "80:80"
#     depends_on:
#       - app

version: '3.8'

services:
  app:
    image: praisephs/fastapi-app:latest
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: praisephs/nginx-proxy:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
